### ISSUE TITLE
No mining rewards after 3.0.3.

### ISSUE THREAD

**Issue by BitVenturesUSA** [ohmplatform/freedom-gpt-electron-app#141]
Windows 10 Enterprise 22H2 on VMware ESXi Intel Xeon Proc

After the 3.0.3 update I noticed that the mining process in the logs is working fine but in the GUI I'm not seeing any metrics at all in any of the fields. I'm hoping this is just a display issue and the earnings will be credited when it is fixed.

**Comment by Darcy-P** [comment]
You should find the issue is resolved if you close and restart FreedomGPT.
Reach out to contact@freedomgpt.com if you had some losses due to calculation error during mining. They may be able to offer some compensation.
